const mongoose = require('mongoose');

const calendarEventSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  title: {
    type: String,
    required: [true, 'Event title is required'],
    trim: true
  },
  description: { type: String, trim: true },
  date: { type: Date, required: true, index: true },
  endDate: Date,
  type: {
    type: String,
    enum: ['resupply', 'meeting', 'product_launch', 'maintenance', 'custom'],
    default: 'custom'
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high'],
    default: 'medium'
  },
  color: { type: String, default: '#4F46E5' },
  // If linked to a material resupply
  materialId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Material'
  },
  isAutoGenerated: { type: Boolean, default: false },
  isCompleted: { type: Boolean, default: false }
}, { timestamps: true });

calendarEventSchema.index({ userId: 1, date: 1 });

module.exports = mongoose.model('CalendarEvent', calendarEventSchema);
